// Code generated by go-swagger; DO NOT EDIT.

package features

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewPublicAPIServiceSetOrganizationFeatureParams creates a new PublicAPIServiceSetOrganizationFeatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceSetOrganizationFeatureParams() *PublicAPIServiceSetOrganizationFeatureParams {
	return &PublicAPIServiceSetOrganizationFeatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceSetOrganizationFeatureParamsWithTimeout creates a new PublicAPIServiceSetOrganizationFeatureParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceSetOrganizationFeatureParamsWithTimeout(timeout time.Duration) *PublicAPIServiceSetOrganizationFeatureParams {
	return &PublicAPIServiceSetOrganizationFeatureParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceSetOrganizationFeatureParamsWithContext creates a new PublicAPIServiceSetOrganizationFeatureParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceSetOrganizationFeatureParamsWithContext(ctx context.Context) *PublicAPIServiceSetOrganizationFeatureParams {
	return &PublicAPIServiceSetOrganizationFeatureParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceSetOrganizationFeatureParamsWithHTTPClient creates a new PublicAPIServiceSetOrganizationFeatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceSetOrganizationFeatureParamsWithHTTPClient(client *http.Client) *PublicAPIServiceSetOrganizationFeatureParams {
	return &PublicAPIServiceSetOrganizationFeatureParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceSetOrganizationFeatureParams contains all the parameters to send to the API endpoint

	for the public Api service set organization feature operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceSetOrganizationFeatureParams struct {

	// Body.
	Body *models.V1SetOrganizationFeatureRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service set organization feature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceSetOrganizationFeatureParams) WithDefaults() *PublicAPIServiceSetOrganizationFeatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service set organization feature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceSetOrganizationFeatureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) WithTimeout(timeout time.Duration) *PublicAPIServiceSetOrganizationFeatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) WithContext(ctx context.Context) *PublicAPIServiceSetOrganizationFeatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) WithHTTPClient(client *http.Client) *PublicAPIServiceSetOrganizationFeatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) WithBody(body *models.V1SetOrganizationFeatureRequest) *PublicAPIServiceSetOrganizationFeatureParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service set organization feature params
func (o *PublicAPIServiceSetOrganizationFeatureParams) SetBody(body *models.V1SetOrganizationFeatureRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceSetOrganizationFeatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
