// Code generated by go-swagger; DO NOT EDIT.

package consensus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new consensus API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for consensus API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ApproveActivity(params *ApproveActivityParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ApproveActivityOK, error)

	RejectActivity(params *RejectActivityParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RejectActivityOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ApproveActivity approves activity

Approve an Activity
*/
func (a *Client) ApproveActivity(params *ApproveActivityParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ApproveActivityOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewApproveActivityParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ApproveActivity",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/approve_activity",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ApproveActivityReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ApproveActivityOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ApproveActivity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RejectActivity rejects activity

Reject an Activity
*/
func (a *Client) RejectActivity(params *RejectActivityParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RejectActivityOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRejectActivityParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RejectActivity",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/reject_activity",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RejectActivityReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RejectActivityOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RejectActivity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
