// Code generated by go-swagger; DO NOT EDIT.

package consensus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// RejectActivityReader is a Reader for the RejectActivity structure.
type RejectActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RejectActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRejectActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRejectActivityOK creates a RejectActivityOK with default headers values
func NewRejectActivityOK() *RejectActivityOK {
	return &RejectActivityOK{}
}

/*
RejectActivityOK describes a response with status code 200, with default header values.

A successful response.
*/
type RejectActivityOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this reject activity o k response has a 2xx status code
func (o *RejectActivityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reject activity o k response has a 3xx status code
func (o *RejectActivityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reject activity o k response has a 4xx status code
func (o *RejectActivityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reject activity o k response has a 5xx status code
func (o *RejectActivityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reject activity o k response a status code equal to that given
func (o *RejectActivityOK) IsCode(code int) bool {
	return code == 200
}

func (o *RejectActivityOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] rejectActivityOK  %+v", 200, o.Payload)
}

func (o *RejectActivityOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] rejectActivityOK  %+v", 200, o.Payload)
}

func (o *RejectActivityOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *RejectActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
