// Code generated by go-swagger; DO NOT EDIT.

package consensus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewRejectActivityParams creates a new RejectActivityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRejectActivityParams() *RejectActivityParams {
	return &RejectActivityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRejectActivityParamsWithTimeout creates a new RejectActivityParams object
// with the ability to set a timeout on a request.
func NewRejectActivityParamsWithTimeout(timeout time.Duration) *RejectActivityParams {
	return &RejectActivityParams{
		timeout: timeout,
	}
}

// NewRejectActivityParamsWithContext creates a new RejectActivityParams object
// with the ability to set a context for a request.
func NewRejectActivityParamsWithContext(ctx context.Context) *RejectActivityParams {
	return &RejectActivityParams{
		Context: ctx,
	}
}

// NewRejectActivityParamsWithHTTPClient creates a new RejectActivityParams object
// with the ability to set a custom HTTPClient for a request.
func NewRejectActivityParamsWithHTTPClient(client *http.Client) *RejectActivityParams {
	return &RejectActivityParams{
		HTTPClient: client,
	}
}

/*
RejectActivityParams contains all the parameters to send to the API endpoint

	for the reject activity operation.

	Typically these are written to a http.Request.
*/
type RejectActivityParams struct {

	// Body.
	Body *models.RejectActivityRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reject activity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RejectActivityParams) WithDefaults() *RejectActivityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reject activity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RejectActivityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reject activity params
func (o *RejectActivityParams) WithTimeout(timeout time.Duration) *RejectActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reject activity params
func (o *RejectActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reject activity params
func (o *RejectActivityParams) WithContext(ctx context.Context) *RejectActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reject activity params
func (o *RejectActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reject activity params
func (o *RejectActivityParams) WithHTTPClient(client *http.Client) *RejectActivityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reject activity params
func (o *RejectActivityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the reject activity params
func (o *RejectActivityParams) WithBody(body *models.RejectActivityRequest) *RejectActivityParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the reject activity params
func (o *RejectActivityParams) SetBody(body *models.RejectActivityRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RejectActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
