// Code generated by go-swagger; DO NOT EDIT.

package invitations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// CreateInvitationsReader is a Reader for the CreateInvitations structure.
type CreateInvitationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInvitationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateInvitationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/create_invitations] CreateInvitations", response, response.Code())
	}
}

// NewCreateInvitationsOK creates a CreateInvitationsOK with default headers values
func NewCreateInvitationsOK() *CreateInvitationsOK {
	return &CreateInvitationsOK{}
}

/*
CreateInvitationsOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateInvitationsOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this create invitations o k response has a 2xx status code
func (o *CreateInvitationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create invitations o k response has a 3xx status code
func (o *CreateInvitationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create invitations o k response has a 4xx status code
func (o *CreateInvitationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create invitations o k response has a 5xx status code
func (o *CreateInvitationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create invitations o k response a status code equal to that given
func (o *CreateInvitationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create invitations o k response
func (o *CreateInvitationsOK) Code() int {
	return 200
}

func (o *CreateInvitationsOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_invitations][%d] createInvitationsOK  %+v", 200, o.Payload)
}

func (o *CreateInvitationsOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_invitations][%d] createInvitationsOK  %+v", 200, o.Payload)
}

func (o *CreateInvitationsOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *CreateInvitationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
