version: "2"
run:
  go: "1.19"
  build-tags:
    - integration
    - integration_api
    - integration_cli
    - integration_k8s
    - integration_provision
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - dupword # too annoying
    - err113
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - gosec
    - ireturn # we return interfaces
    - maintidx
    - mnd
    - nestif
    - nilnil # we return "nil, nil"
    - nolintlint
    - nonamedreturns
    - paralleltest
    - promlinter # https://github.com/golangci/golangci-lint/issues/2222
    - rowserrcheck 
    - sqlclosecheck
    - tagliatelle # we have many different conventions
    - thelper
    - varnamelen # too annoying
    - wastedassign
    - wrapcheck
    - godot # too annoying
    - nlreturn # super nit picky
    - noinlineerr # no need
    - perfsprint # annoying
    - recvcheck # false positives with interfaces
    - staticcheck
    - testifylint # too many issues
    - unconvert
    - usetesting
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/golang/protobuf/proto
              desc: not allowed
            - pkg: google.golang.org/protobuf/proto
              desc: not allowed
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gomoddirectives:
      replace-allow-list:
        - gopkg.in/yaml.v3
        - inet.af/tcpproxy
      replace-local: true
      exclude-forbidden: true
      retract-allow-no-explanation: false
    lll:
      line-length: 200
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: unexported-return
          disabled: true
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: pkg/api
        text: should have a package comment
      - path: (.+)\.go$
        text: package comment should be of the form "Package services ..."
      - path: (.+)\.go$
        text: ^ST1000
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tkhq)
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
