version: "2"

run:
  timeout: 10m
  build-tags:
    - integration
    - integration_api
    - integration_cli
    - integration_k8s
    - integration_provision

linters:
  enable:
    - errcheck
    - exhaustive
    - govet
    - gocyclo
    - dupl
    - goconst
    - misspell
    - lll
    - revive
    - nakedret
    - nolintlint
    - prealloc
    - cyclop
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      shadow:
        strict: true
    gocyclo:
      min-complexity: 10
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    lll:
      line-length: 200
      tab-width: 1
    revive:
      rules:
        - name: unexported-return
          disabled: true
    nakedret:
      max-func-lines: 30
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    cyclop:
      max-complexity: 20
  exclusions:
    generated: lax
    paths:
      - pkg/api/client$
      - .*\.pb\.go$
    text:
      - "package comment should be of the form"
      - "^ST1000"

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gofmt:
      simplify: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tkhq)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - pkg/api/client$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
