// Code generated by go-swagger; DO NOT EDIT.

package boot_proof

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new boot proof API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for boot proof API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetBootProof(params *GetBootProofParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBootProofOK, error)

	GetLatestBootProof(params *GetLatestBootProofParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLatestBootProofOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetBootProof gets a specific boot proof

Get the boot proof for a given ephemeral key.
*/
func (a *Client) GetBootProof(params *GetBootProofParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBootProofOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBootProofParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetBootProof",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_boot_proof",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBootProofReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBootProofOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBootProof: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetLatestBootProof gets the latest boot proof for an app

Get the latest boot proof for a given enclave app name.
*/
func (a *Client) GetLatestBootProof(params *GetLatestBootProofParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetLatestBootProofOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLatestBootProofParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetLatestBootProof",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_latest_boot_proof",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetLatestBootProofReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLatestBootProofOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetLatestBootProof: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
