// Code generated by go-swagger; DO NOT EDIT.

package activities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// PublicAPIServiceRejectActivityReader is a Reader for the PublicAPIServiceRejectActivity structure.
type PublicAPIServiceRejectActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceRejectActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceRejectActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicAPIServiceRejectActivityForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicAPIServiceRejectActivityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPublicAPIServiceRejectActivityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceRejectActivityOK creates a PublicAPIServiceRejectActivityOK with default headers values
func NewPublicAPIServiceRejectActivityOK() *PublicAPIServiceRejectActivityOK {
	return &PublicAPIServiceRejectActivityOK{}
}

/*
PublicAPIServiceRejectActivityOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceRejectActivityOK struct {
	Payload *models.V1ActivityResponse
}

// IsSuccess returns true when this public Api service reject activity o k response has a 2xx status code
func (o *PublicAPIServiceRejectActivityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service reject activity o k response has a 3xx status code
func (o *PublicAPIServiceRejectActivityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service reject activity o k response has a 4xx status code
func (o *PublicAPIServiceRejectActivityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service reject activity o k response has a 5xx status code
func (o *PublicAPIServiceRejectActivityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service reject activity o k response a status code equal to that given
func (o *PublicAPIServiceRejectActivityOK) IsCode(code int) bool {
	return code == 200
}

func (o *PublicAPIServiceRejectActivityOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceRejectActivityOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceRejectActivityOK) GetPayload() *models.V1ActivityResponse {
	return o.Payload
}

func (o *PublicAPIServiceRejectActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceRejectActivityForbidden creates a PublicAPIServiceRejectActivityForbidden with default headers values
func NewPublicAPIServiceRejectActivityForbidden() *PublicAPIServiceRejectActivityForbidden {
	return &PublicAPIServiceRejectActivityForbidden{}
}

/*
PublicAPIServiceRejectActivityForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type PublicAPIServiceRejectActivityForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this public Api service reject activity forbidden response has a 2xx status code
func (o *PublicAPIServiceRejectActivityForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service reject activity forbidden response has a 3xx status code
func (o *PublicAPIServiceRejectActivityForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service reject activity forbidden response has a 4xx status code
func (o *PublicAPIServiceRejectActivityForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service reject activity forbidden response has a 5xx status code
func (o *PublicAPIServiceRejectActivityForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service reject activity forbidden response a status code equal to that given
func (o *PublicAPIServiceRejectActivityForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *PublicAPIServiceRejectActivityForbidden) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceRejectActivityForbidden) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceRejectActivityForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PublicAPIServiceRejectActivityForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceRejectActivityNotFound creates a PublicAPIServiceRejectActivityNotFound with default headers values
func NewPublicAPIServiceRejectActivityNotFound() *PublicAPIServiceRejectActivityNotFound {
	return &PublicAPIServiceRejectActivityNotFound{}
}

/*
PublicAPIServiceRejectActivityNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type PublicAPIServiceRejectActivityNotFound struct {
	Payload string
}

// IsSuccess returns true when this public Api service reject activity not found response has a 2xx status code
func (o *PublicAPIServiceRejectActivityNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service reject activity not found response has a 3xx status code
func (o *PublicAPIServiceRejectActivityNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service reject activity not found response has a 4xx status code
func (o *PublicAPIServiceRejectActivityNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service reject activity not found response has a 5xx status code
func (o *PublicAPIServiceRejectActivityNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service reject activity not found response a status code equal to that given
func (o *PublicAPIServiceRejectActivityNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PublicAPIServiceRejectActivityNotFound) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceRejectActivityNotFound) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] publicApiServiceRejectActivityNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceRejectActivityNotFound) GetPayload() string {
	return o.Payload
}

func (o *PublicAPIServiceRejectActivityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceRejectActivityDefault creates a PublicAPIServiceRejectActivityDefault with default headers values
func NewPublicAPIServiceRejectActivityDefault(code int) *PublicAPIServiceRejectActivityDefault {
	return &PublicAPIServiceRejectActivityDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceRejectActivityDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceRejectActivityDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the public Api service reject activity default response
func (o *PublicAPIServiceRejectActivityDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this public Api service reject activity default response has a 2xx status code
func (o *PublicAPIServiceRejectActivityDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service reject activity default response has a 3xx status code
func (o *PublicAPIServiceRejectActivityDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service reject activity default response has a 4xx status code
func (o *PublicAPIServiceRejectActivityDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service reject activity default response has a 5xx status code
func (o *PublicAPIServiceRejectActivityDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service reject activity default response a status code equal to that given
func (o *PublicAPIServiceRejectActivityDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PublicAPIServiceRejectActivityDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] PublicApiService_RejectActivity default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceRejectActivityDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/reject_activity][%d] PublicApiService_RejectActivity default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceRejectActivityDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceRejectActivityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
