// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewUpdateRootQuorumParams creates a new UpdateRootQuorumParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRootQuorumParams() *UpdateRootQuorumParams {
	return &UpdateRootQuorumParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRootQuorumParamsWithTimeout creates a new UpdateRootQuorumParams object
// with the ability to set a timeout on a request.
func NewUpdateRootQuorumParamsWithTimeout(timeout time.Duration) *UpdateRootQuorumParams {
	return &UpdateRootQuorumParams{
		timeout: timeout,
	}
}

// NewUpdateRootQuorumParamsWithContext creates a new UpdateRootQuorumParams object
// with the ability to set a context for a request.
func NewUpdateRootQuorumParamsWithContext(ctx context.Context) *UpdateRootQuorumParams {
	return &UpdateRootQuorumParams{
		Context: ctx,
	}
}

// NewUpdateRootQuorumParamsWithHTTPClient creates a new UpdateRootQuorumParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRootQuorumParamsWithHTTPClient(client *http.Client) *UpdateRootQuorumParams {
	return &UpdateRootQuorumParams{
		HTTPClient: client,
	}
}

/*
UpdateRootQuorumParams contains all the parameters to send to the API endpoint

	for the update root quorum operation.

	Typically these are written to a http.Request.
*/
type UpdateRootQuorumParams struct {

	// Body.
	Body *models.UpdateRootQuorumRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update root quorum params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRootQuorumParams) WithDefaults() *UpdateRootQuorumParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update root quorum params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRootQuorumParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update root quorum params
func (o *UpdateRootQuorumParams) WithTimeout(timeout time.Duration) *UpdateRootQuorumParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update root quorum params
func (o *UpdateRootQuorumParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update root quorum params
func (o *UpdateRootQuorumParams) WithContext(ctx context.Context) *UpdateRootQuorumParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update root quorum params
func (o *UpdateRootQuorumParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update root quorum params
func (o *UpdateRootQuorumParams) WithHTTPClient(client *http.Client) *UpdateRootQuorumParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update root quorum params
func (o *UpdateRootQuorumParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update root quorum params
func (o *UpdateRootQuorumParams) WithBody(body *models.UpdateRootQuorumRequest) *UpdateRootQuorumParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update root quorum params
func (o *UpdateRootQuorumParams) SetBody(body *models.UpdateRootQuorumRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRootQuorumParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
