// Code generated by go-swagger; DO NOT EDIT.

package user_verification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// InitOtpReader is a Reader for the InitOtp structure.
type InitOtpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitOtpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInitOtpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/init_otp] InitOtp", response, response.Code())
	}
}

// NewInitOtpOK creates a InitOtpOK with default headers values
func NewInitOtpOK() *InitOtpOK {
	return &InitOtpOK{}
}

/*
InitOtpOK describes a response with status code 200, with default header values.

A successful response.
*/
type InitOtpOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this init otp o k response has a 2xx status code
func (o *InitOtpOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this init otp o k response has a 3xx status code
func (o *InitOtpOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this init otp o k response has a 4xx status code
func (o *InitOtpOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this init otp o k response has a 5xx status code
func (o *InitOtpOK) IsServerError() bool {
	return false
}

// IsCode returns true when this init otp o k response a status code equal to that given
func (o *InitOtpOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the init otp o k response
func (o *InitOtpOK) Code() int {
	return 200
}

func (o *InitOtpOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/init_otp][%d] initOtpOK  %+v", 200, o.Payload)
}

func (o *InitOtpOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/init_otp][%d] initOtpOK  %+v", 200, o.Payload)
}

func (o *InitOtpOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *InitOtpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
