// Code generated by go-swagger; DO NOT EDIT.

package public_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// PublicAPIServiceCreateWalletAccountsReader is a Reader for the PublicAPIServiceCreateWalletAccounts structure.
type PublicAPIServiceCreateWalletAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceCreateWalletAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceCreateWalletAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPublicAPIServiceCreateWalletAccountsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceCreateWalletAccountsOK creates a PublicAPIServiceCreateWalletAccountsOK with default headers values
func NewPublicAPIServiceCreateWalletAccountsOK() *PublicAPIServiceCreateWalletAccountsOK {
	return &PublicAPIServiceCreateWalletAccountsOK{}
}

/*
PublicAPIServiceCreateWalletAccountsOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceCreateWalletAccountsOK struct {
	Payload *models.V1ActivityResponse
}

// IsSuccess returns true when this public Api service create wallet accounts o k response has a 2xx status code
func (o *PublicAPIServiceCreateWalletAccountsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service create wallet accounts o k response has a 3xx status code
func (o *PublicAPIServiceCreateWalletAccountsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service create wallet accounts o k response has a 4xx status code
func (o *PublicAPIServiceCreateWalletAccountsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service create wallet accounts o k response has a 5xx status code
func (o *PublicAPIServiceCreateWalletAccountsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service create wallet accounts o k response a status code equal to that given
func (o *PublicAPIServiceCreateWalletAccountsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service create wallet accounts o k response
func (o *PublicAPIServiceCreateWalletAccountsOK) Code() int {
	return 200
}

func (o *PublicAPIServiceCreateWalletAccountsOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_wallet_accounts][%d] publicApiServiceCreateWalletAccountsOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceCreateWalletAccountsOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_wallet_accounts][%d] publicApiServiceCreateWalletAccountsOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceCreateWalletAccountsOK) GetPayload() *models.V1ActivityResponse {
	return o.Payload
}

func (o *PublicAPIServiceCreateWalletAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceCreateWalletAccountsDefault creates a PublicAPIServiceCreateWalletAccountsDefault with default headers values
func NewPublicAPIServiceCreateWalletAccountsDefault(code int) *PublicAPIServiceCreateWalletAccountsDefault {
	return &PublicAPIServiceCreateWalletAccountsDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceCreateWalletAccountsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceCreateWalletAccountsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service create wallet accounts default response has a 2xx status code
func (o *PublicAPIServiceCreateWalletAccountsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service create wallet accounts default response has a 3xx status code
func (o *PublicAPIServiceCreateWalletAccountsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service create wallet accounts default response has a 4xx status code
func (o *PublicAPIServiceCreateWalletAccountsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service create wallet accounts default response has a 5xx status code
func (o *PublicAPIServiceCreateWalletAccountsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service create wallet accounts default response a status code equal to that given
func (o *PublicAPIServiceCreateWalletAccountsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service create wallet accounts default response
func (o *PublicAPIServiceCreateWalletAccountsDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceCreateWalletAccountsDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_wallet_accounts][%d] PublicApiService_CreateWalletAccounts default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceCreateWalletAccountsDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_wallet_accounts][%d] PublicApiService_CreateWalletAccounts default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceCreateWalletAccountsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceCreateWalletAccountsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
