// Code generated by go-swagger; DO NOT EDIT.

package public_api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewPublicAPIServiceSignRawPayloadV2Params creates a new PublicAPIServiceSignRawPayloadV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceSignRawPayloadV2Params() *PublicAPIServiceSignRawPayloadV2Params {
	return &PublicAPIServiceSignRawPayloadV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceSignRawPayloadV2ParamsWithTimeout creates a new PublicAPIServiceSignRawPayloadV2Params object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceSignRawPayloadV2ParamsWithTimeout(timeout time.Duration) *PublicAPIServiceSignRawPayloadV2Params {
	return &PublicAPIServiceSignRawPayloadV2Params{
		timeout: timeout,
	}
}

// NewPublicAPIServiceSignRawPayloadV2ParamsWithContext creates a new PublicAPIServiceSignRawPayloadV2Params object
// with the ability to set a context for a request.
func NewPublicAPIServiceSignRawPayloadV2ParamsWithContext(ctx context.Context) *PublicAPIServiceSignRawPayloadV2Params {
	return &PublicAPIServiceSignRawPayloadV2Params{
		Context: ctx,
	}
}

// NewPublicAPIServiceSignRawPayloadV2ParamsWithHTTPClient creates a new PublicAPIServiceSignRawPayloadV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceSignRawPayloadV2ParamsWithHTTPClient(client *http.Client) *PublicAPIServiceSignRawPayloadV2Params {
	return &PublicAPIServiceSignRawPayloadV2Params{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceSignRawPayloadV2Params contains all the parameters to send to the API endpoint

	for the public Api service sign raw payload v2 operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceSignRawPayloadV2Params struct {

	// Body.
	Body *models.V1SignRawPayloadV2Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service sign raw payload v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceSignRawPayloadV2Params) WithDefaults() *PublicAPIServiceSignRawPayloadV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service sign raw payload v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceSignRawPayloadV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) WithTimeout(timeout time.Duration) *PublicAPIServiceSignRawPayloadV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) WithContext(ctx context.Context) *PublicAPIServiceSignRawPayloadV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) WithHTTPClient(client *http.Client) *PublicAPIServiceSignRawPayloadV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) WithBody(body *models.V1SignRawPayloadV2Request) *PublicAPIServiceSignRawPayloadV2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service sign raw payload v2 params
func (o *PublicAPIServiceSignRawPayloadV2Params) SetBody(body *models.V1SignRawPayloadV2Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceSignRawPayloadV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
