// Code generated by go-swagger; DO NOT EDIT.

package wallets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// DeleteWalletsReader is a Reader for the DeleteWallets structure.
type DeleteWalletsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWalletsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteWalletsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/delete_wallets] DeleteWallets", response, response.Code())
	}
}

// NewDeleteWalletsOK creates a DeleteWalletsOK with default headers values
func NewDeleteWalletsOK() *DeleteWalletsOK {
	return &DeleteWalletsOK{}
}

/*
DeleteWalletsOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteWalletsOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this delete wallets o k response has a 2xx status code
func (o *DeleteWalletsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete wallets o k response has a 3xx status code
func (o *DeleteWalletsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete wallets o k response has a 4xx status code
func (o *DeleteWalletsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete wallets o k response has a 5xx status code
func (o *DeleteWalletsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete wallets o k response a status code equal to that given
func (o *DeleteWalletsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete wallets o k response
func (o *DeleteWalletsOK) Code() int {
	return 200
}

func (o *DeleteWalletsOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_wallets][%d] deleteWalletsOK  %+v", 200, o.Payload)
}

func (o *DeleteWalletsOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_wallets][%d] deleteWalletsOK  %+v", 200, o.Payload)
}

func (o *DeleteWalletsOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *DeleteWalletsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
