// Code generated by go-swagger; DO NOT EDIT.

package wallets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewListSupportedAssetsParams creates a new ListSupportedAssetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSupportedAssetsParams() *ListSupportedAssetsParams {
	return &ListSupportedAssetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSupportedAssetsParamsWithTimeout creates a new ListSupportedAssetsParams object
// with the ability to set a timeout on a request.
func NewListSupportedAssetsParamsWithTimeout(timeout time.Duration) *ListSupportedAssetsParams {
	return &ListSupportedAssetsParams{
		timeout: timeout,
	}
}

// NewListSupportedAssetsParamsWithContext creates a new ListSupportedAssetsParams object
// with the ability to set a context for a request.
func NewListSupportedAssetsParamsWithContext(ctx context.Context) *ListSupportedAssetsParams {
	return &ListSupportedAssetsParams{
		Context: ctx,
	}
}

// NewListSupportedAssetsParamsWithHTTPClient creates a new ListSupportedAssetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSupportedAssetsParamsWithHTTPClient(client *http.Client) *ListSupportedAssetsParams {
	return &ListSupportedAssetsParams{
		HTTPClient: client,
	}
}

/*
ListSupportedAssetsParams contains all the parameters to send to the API endpoint

	for the list supported assets operation.

	Typically these are written to a http.Request.
*/
type ListSupportedAssetsParams struct {

	// Body.
	Body *models.ListSupportedAssetsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list supported assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSupportedAssetsParams) WithDefaults() *ListSupportedAssetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list supported assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSupportedAssetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list supported assets params
func (o *ListSupportedAssetsParams) WithTimeout(timeout time.Duration) *ListSupportedAssetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list supported assets params
func (o *ListSupportedAssetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list supported assets params
func (o *ListSupportedAssetsParams) WithContext(ctx context.Context) *ListSupportedAssetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list supported assets params
func (o *ListSupportedAssetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list supported assets params
func (o *ListSupportedAssetsParams) WithHTTPClient(client *http.Client) *ListSupportedAssetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list supported assets params
func (o *ListSupportedAssetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list supported assets params
func (o *ListSupportedAssetsParams) WithBody(body *models.ListSupportedAssetsRequest) *ListSupportedAssetsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list supported assets params
func (o *ListSupportedAssetsParams) SetBody(body *models.ListSupportedAssetsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListSupportedAssetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
