// Code generated by go-swagger; DO NOT EDIT.

package private_key_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewCreatePrivateKeyTagParams creates a new CreatePrivateKeyTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePrivateKeyTagParams() *CreatePrivateKeyTagParams {
	return &CreatePrivateKeyTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePrivateKeyTagParamsWithTimeout creates a new CreatePrivateKeyTagParams object
// with the ability to set a timeout on a request.
func NewCreatePrivateKeyTagParamsWithTimeout(timeout time.Duration) *CreatePrivateKeyTagParams {
	return &CreatePrivateKeyTagParams{
		timeout: timeout,
	}
}

// NewCreatePrivateKeyTagParamsWithContext creates a new CreatePrivateKeyTagParams object
// with the ability to set a context for a request.
func NewCreatePrivateKeyTagParamsWithContext(ctx context.Context) *CreatePrivateKeyTagParams {
	return &CreatePrivateKeyTagParams{
		Context: ctx,
	}
}

// NewCreatePrivateKeyTagParamsWithHTTPClient creates a new CreatePrivateKeyTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePrivateKeyTagParamsWithHTTPClient(client *http.Client) *CreatePrivateKeyTagParams {
	return &CreatePrivateKeyTagParams{
		HTTPClient: client,
	}
}

/*
CreatePrivateKeyTagParams contains all the parameters to send to the API endpoint

	for the create private key tag operation.

	Typically these are written to a http.Request.
*/
type CreatePrivateKeyTagParams struct {

	// Body.
	Body *models.CreatePrivateKeyTagRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create private key tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePrivateKeyTagParams) WithDefaults() *CreatePrivateKeyTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create private key tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePrivateKeyTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create private key tag params
func (o *CreatePrivateKeyTagParams) WithTimeout(timeout time.Duration) *CreatePrivateKeyTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create private key tag params
func (o *CreatePrivateKeyTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create private key tag params
func (o *CreatePrivateKeyTagParams) WithContext(ctx context.Context) *CreatePrivateKeyTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create private key tag params
func (o *CreatePrivateKeyTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create private key tag params
func (o *CreatePrivateKeyTagParams) WithHTTPClient(client *http.Client) *CreatePrivateKeyTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create private key tag params
func (o *CreatePrivateKeyTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create private key tag params
func (o *CreatePrivateKeyTagParams) WithBody(body *models.CreatePrivateKeyTagRequest) *CreatePrivateKeyTagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create private key tag params
func (o *CreatePrivateKeyTagParams) SetBody(body *models.CreatePrivateKeyTagRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePrivateKeyTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
