// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewDeleteAPIKeysParams creates a new DeleteAPIKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIKeysParams() *DeleteAPIKeysParams {
	return &DeleteAPIKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIKeysParamsWithTimeout creates a new DeleteAPIKeysParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIKeysParamsWithTimeout(timeout time.Duration) *DeleteAPIKeysParams {
	return &DeleteAPIKeysParams{
		timeout: timeout,
	}
}

// NewDeleteAPIKeysParamsWithContext creates a new DeleteAPIKeysParams object
// with the ability to set a context for a request.
func NewDeleteAPIKeysParamsWithContext(ctx context.Context) *DeleteAPIKeysParams {
	return &DeleteAPIKeysParams{
		Context: ctx,
	}
}

// NewDeleteAPIKeysParamsWithHTTPClient creates a new DeleteAPIKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIKeysParamsWithHTTPClient(client *http.Client) *DeleteAPIKeysParams {
	return &DeleteAPIKeysParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIKeysParams contains all the parameters to send to the API endpoint

	for the delete Api keys operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIKeysParams struct {

	// Body.
	Body *models.DeleteAPIKeysRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete Api keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIKeysParams) WithDefaults() *DeleteAPIKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete Api keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete Api keys params
func (o *DeleteAPIKeysParams) WithTimeout(timeout time.Duration) *DeleteAPIKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Api keys params
func (o *DeleteAPIKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Api keys params
func (o *DeleteAPIKeysParams) WithContext(ctx context.Context) *DeleteAPIKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Api keys params
func (o *DeleteAPIKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Api keys params
func (o *DeleteAPIKeysParams) WithHTTPClient(client *http.Client) *DeleteAPIKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Api keys params
func (o *DeleteAPIKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete Api keys params
func (o *DeleteAPIKeysParams) WithBody(body *models.DeleteAPIKeysRequest) *DeleteAPIKeysParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete Api keys params
func (o *DeleteAPIKeysParams) SetBody(body *models.DeleteAPIKeysRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
