// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// UpdateUserEmailReader is a Reader for the UpdateUserEmail structure.
type UpdateUserEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateUserEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateUserEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/update_user_email] UpdateUserEmail", response, response.Code())
	}
}

// NewUpdateUserEmailOK creates a UpdateUserEmailOK with default headers values
func NewUpdateUserEmailOK() *UpdateUserEmailOK {
	return &UpdateUserEmailOK{}
}

/*
UpdateUserEmailOK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdateUserEmailOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this update user email o k response has a 2xx status code
func (o *UpdateUserEmailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update user email o k response has a 3xx status code
func (o *UpdateUserEmailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update user email o k response has a 4xx status code
func (o *UpdateUserEmailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update user email o k response has a 5xx status code
func (o *UpdateUserEmailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update user email o k response a status code equal to that given
func (o *UpdateUserEmailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update user email o k response
func (o *UpdateUserEmailOK) Code() int {
	return 200
}

func (o *UpdateUserEmailOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/update_user_email][%d] updateUserEmailOK  %+v", 200, o.Payload)
}

func (o *UpdateUserEmailOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/update_user_email][%d] updateUserEmailOK  %+v", 200, o.Payload)
}

func (o *UpdateUserEmailOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *UpdateUserEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
