package generators

import (
	"fmt"
	"strconv"
	"strings"
)

type fieldSpec struct {
	JSONName    string
	GoName      string
	GoType      string
	Description string
	Required    bool
}

func (g *generator) generateModels() string {
	var b strings.Builder
	b.WriteString(`// Code generated by go run ./codegen; DO NOT EDIT.

package turnkey

import "encoding/json"

`)

	for _, raw := range sortedKeys(g.definitions) {
		def := g.definitions[raw]
		if isEnum(def) {
			g.writeEnum(&b, raw, def)
		}
	}

	for _, raw := range sortedKeys(g.definitions) {
		def := g.definitions[raw]
		if isEnum(def) {
			continue
		}

		if isActivityWireBody(def) {
			continue
		}

		g.writeModel(&b, raw, def)
	}

	for _, op := range g.operations {
		if op.MethodType == methodTypeCommand || op.MethodType == methodTypeActivityDecision {
			g.writeActivityInput(&b, op)
			responseName := op.MethodName + "Response"
			fmt.Fprintf(&b, "type %s struct {\n", responseName)
			fmt.Fprint(&b, "\tActivity Activity `json:\"activity\"`\n")

			if op.ResultDef != "" {
				fmt.Fprintf(&b, "\t%s\n", g.goName(op.ResultDef))
			}

			fmt.Fprint(&b, "}\n\n")
		}
	}

	return b.String()
}

func (g *generator) writeEnum(b *strings.Builder, raw string, def *schema) {
	name := g.goName(raw)
	fmt.Fprintf(b, "type %s string\n\nconst (\n", name)

	used := map[string]bool{}

	for _, value := range def.Enum {
		constName := name + exportedName(enumSuffix(name, value))
		if used[constName] {
			constName += strconv.Itoa(len(used))
		}

		used[constName] = true
		fmt.Fprintf(b, "\t%s %s = %q\n", constName, name, value)
	}

	fmt.Fprint(b, ")\n\n")
}

func (g *generator) writeModel(b *strings.Builder, raw string, def *schema) {
	name := g.goName(raw)
	if def.Type != typeObject || len(def.Properties) == 0 {
		fmt.Fprintf(b, "type %s map[string]any\n\n", name)
		return
	}

	fields := g.fieldsFromSchema(def)

	fmt.Fprintf(b, "type %s struct {\n", name)

	for _, f := range fields {
		writeDoc(b, f.Description, "\t")

		omitempty := ""
		if !f.Required {
			omitempty = ",omitempty"
		}

		fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.GoName, f.GoType, f.JSONName+omitempty)
	}

	if def.AdditionalProperties != nil {
		fmt.Fprint(b, "\tAdditionalProperties map[string]any `json:\"-\"`\n")
	}

	fmt.Fprint(b, "}\n\n")

	if def.AdditionalProperties != nil {
		g.writeAdditionalPropertiesMethods(b, name, fields)
	}
}

func (g *generator) writeAdditionalPropertiesMethods(b *strings.Builder, name string, fields []fieldSpec) {
	fmt.Fprintf(b, "func (m *%s) UnmarshalJSON(data []byte) error {\n", name)
	fmt.Fprintf(b, "\ttype alias %s\n", name)
	fmt.Fprint(b, "\tvar known alias\n")
	fmt.Fprint(b, "\tif err := json.Unmarshal(data, &known); err != nil { return err }\n")
	fmt.Fprint(b, "\t*m = ")
	fmt.Fprintf(b, "%s(known)\n", name)
	fmt.Fprint(b, "\tvar raw map[string]any\n")
	fmt.Fprint(b, "\tif err := json.Unmarshal(data, &raw); err != nil { return err }\n")

	for _, f := range fields {
		fmt.Fprintf(b, "\tdelete(raw, %q)\n", f.JSONName)
	}

	fmt.Fprint(b, "\tif len(raw) > 0 { m.AdditionalProperties = raw }\n")
	fmt.Fprint(b, "\treturn nil\n")
	fmt.Fprint(b, "}\n\n")

	fmt.Fprintf(b, "func (m %s) MarshalJSON() ([]byte, error) {\n", name)
	fmt.Fprintf(b, "\ttype alias %s\n", name)
	fmt.Fprint(b, "\tdata, err := json.Marshal(alias(m))\n")
	fmt.Fprint(b, "\tif err != nil { return nil, err }\n")
	fmt.Fprint(b, "\tif len(m.AdditionalProperties) == 0 { return data, nil }\n")
	fmt.Fprint(b, "\tvar raw map[string]any\n")
	fmt.Fprint(b, "\tif err := json.Unmarshal(data, &raw); err != nil { return nil, err }\n")
	fmt.Fprint(b, "\tfor k, v := range m.AdditionalProperties { raw[k] = v }\n")
	fmt.Fprint(b, "\treturn json.Marshal(raw)\n")
	fmt.Fprint(b, "}\n\n")
}

func (g *generator) writeActivityInput(b *strings.Builder, op operationInfo) {
	requestName := op.MethodName + "Request"
	fmt.Fprintf(b, "type %s struct {\n", requestName)
	fmt.Fprint(b, "\t// OrganizationID defaults to the client's organization ID. Override only when targeting a sub-organization.\n")
	fmt.Fprint(b, "\tOrganizationID string `json:\"organizationId,omitempty\"`\n")
	fmt.Fprint(b, "\t// TimestampMs is set automatically to the current time. Override only if you need a specific timestamp.\n")
	fmt.Fprint(b, "\tTimestampMs string `json:\"timestampMs,omitempty\"`\n")

	def := g.definitions[op.IntentDef]
	if def != nil {
		for _, f := range g.fieldsFromSchema(def) {
			omitempty := ""
			if !f.Required {
				omitempty = ",omitempty"
			}

			writeDoc(b, f.Description, "\t")
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.GoName, f.GoType, f.JSONName+omitempty)
		}
	}

	fmt.Fprint(b, "}\n\n")
	fmt.Fprintf(b, "func (%s) ActivityType() string { return %q }\n\n", requestName, op.ActivityType)
}

func (g *generator) fieldsFromSchema(def *schema) []fieldSpec {
	required := map[string]bool{}
	for _, name := range def.Required {
		required[name] = true
	}

	fields := make([]fieldSpec, 0, len(def.Properties))
	for _, jsonName := range sortedKeys(def.Properties) {
		prop := def.Properties[jsonName]
		goType := g.goType(prop, required[jsonName])
		fields = append(fields, fieldSpec{
			JSONName:    jsonName,
			GoName:      fieldName(jsonName),
			GoType:      goType,
			Description: prop.Description,
			Required:    required[jsonName] || shouldEmitEmptyArray(prop),
		})
	}

	return fields
}

//nolint:gocyclo
func (g *generator) goType(s *schema, required bool) string {
	if s == nil {
		return goTypeAny
	}

	if s.Ref != "" {
		name := g.goName(refName(s.Ref))
		if required {
			return name
		}

		return "*" + name
	}

	switch s.Type {
	case goTypeString:
		if len(s.Enum) > 0 {
			return goTypeString
		}

		if required {
			return goTypeString
		}

		return "*" + goTypeString
	case "boolean":
		if required {
			return "bool"
		}

		return "*bool"
	case "integer":
		t := "int64"
		if s.Format == "int32" {
			t = "int"
		}

		if required {
			return t
		}

		return "*" + t
	case "number":
		if required {
			return "float64"
		}

		return "*float64"
	case "array":
		return "[]" + g.goType(arrayItem(s.Items), true)
	case typeObject:
		return goTypeMapStringAny
	default:
		return goTypeAny
	}
}

func arrayItem(s *schema) *schema {
	if s == nil {
		return &schema{Type: typeObject}
	}

	return s
}

func isEnum(def *schema) bool {
	return def != nil && def.Type == "string" && len(def.Enum) > 0
}

func shouldEmitEmptyArray(s *schema) bool {
	return s != nil &&
		s.Type == "array" &&
		strings.Contains(strings.ToLower(s.Description), "should be an empty array")
}
