// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ActivityV1AccessType activity v1 access type
//
// swagger:model activity.v1.AccessType
type ActivityV1AccessType string

func NewActivityV1AccessType(value ActivityV1AccessType) *ActivityV1AccessType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ActivityV1AccessType.
func (m ActivityV1AccessType) Pointer() *ActivityV1AccessType {
	return &m
}

const (

	// AccessTypeWeb captures enum value "ACCESS_TYPE_WEB"
	AccessTypeWeb ActivityV1AccessType = "ACCESS_TYPE_WEB"

	// AccessTypeAPI captures enum value "ACCESS_TYPE_API"
	AccessTypeAPI ActivityV1AccessType = "ACCESS_TYPE_API"

	// AccessTypeAll captures enum value "ACCESS_TYPE_ALL"
	AccessTypeAll ActivityV1AccessType = "ACCESS_TYPE_ALL"
)

// for schema
var ActivityV1AccessTypeEnum []ActivityV1AccessType

func init() {
	var res []ActivityV1AccessType
	if err := json.Unmarshal([]byte(`["ACCESS_TYPE_WEB","ACCESS_TYPE_API","ACCESS_TYPE_ALL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ActivityV1AccessTypeEnum = append(ActivityV1AccessTypeEnum, v)
	}
}

func (m ActivityV1AccessType) validateActivityV1AccessTypeEnum(path, location string, value ActivityV1AccessType) error {
	if err := validate.EnumCase(path, location, value, ActivityV1AccessTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this activity v1 access type
func (m ActivityV1AccessType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateActivityV1AccessTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this activity v1 access type based on context it is used
func (m ActivityV1AccessType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
