// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BootProof boot proof
//
// swagger:model BootProof
type BootProof struct {

	// The DER encoded COSE Sign1 struct Attestation doc.
	// Required: true
	AwsAttestationDocB64 *string `json:"awsAttestationDocB64"`

	// created at
	// Required: true
	CreatedAt *ExternalDataV1Timestamp `json:"createdAt"`

	// The label under which the enclave app was deployed.
	// Required: true
	DeploymentLabel *string `json:"deploymentLabel"`

	// Name of the enclave app
	// Required: true
	EnclaveApp *string `json:"enclaveApp"`

	// The hex encoded Ephemeral Public Key.
	// Required: true
	EphemeralPublicKeyHex *string `json:"ephemeralPublicKeyHex"`

	// Owner of the app i.e. 'tkhq'
	// Required: true
	Owner *string `json:"owner"`

	// The borsch serialized base64 encoded Manifest.
	// Required: true
	QosManifestB64 *string `json:"qosManifestB64"`

	// The borsch serialized base64 encoded Manifest Envelope.
	// Required: true
	QosManifestEnvelopeB64 *string `json:"qosManifestEnvelopeB64"`
}

// Validate validates this boot proof
func (m *BootProof) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwsAttestationDocB64(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeploymentLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnclaveApp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEphemeralPublicKeyHex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQosManifestB64(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQosManifestEnvelopeB64(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BootProof) validateAwsAttestationDocB64(formats strfmt.Registry) error {

	if err := validate.Required("awsAttestationDocB64", "body", m.AwsAttestationDocB64); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("createdAt", "body", m.CreatedAt); err != nil {
		return err
	}

	if m.CreatedAt != nil {
		if err := m.CreatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *BootProof) validateDeploymentLabel(formats strfmt.Registry) error {

	if err := validate.Required("deploymentLabel", "body", m.DeploymentLabel); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateEnclaveApp(formats strfmt.Registry) error {

	if err := validate.Required("enclaveApp", "body", m.EnclaveApp); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateEphemeralPublicKeyHex(formats strfmt.Registry) error {

	if err := validate.Required("ephemeralPublicKeyHex", "body", m.EphemeralPublicKeyHex); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateOwner(formats strfmt.Registry) error {

	if err := validate.Required("owner", "body", m.Owner); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateQosManifestB64(formats strfmt.Registry) error {

	if err := validate.Required("qosManifestB64", "body", m.QosManifestB64); err != nil {
		return err
	}

	return nil
}

func (m *BootProof) validateQosManifestEnvelopeB64(formats strfmt.Registry) error {

	if err := validate.Required("qosManifestEnvelopeB64", "body", m.QosManifestEnvelopeB64); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this boot proof based on the context it is used
func (m *BootProof) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BootProof) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedAt != nil {

		if err := m.CreatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BootProof) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BootProof) UnmarshalBinary(b []byte) error {
	var res BootProof
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
