// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTvcDeploymentIntent create tvc deployment intent
//
// swagger:model CreateTvcDeploymentIntent
type CreateTvcDeploymentIntent struct {

	// The unique identifier of the to-be-deployed TVC application
	// Required: true
	AppID *string `json:"appId"`

	// Optional flag to indicate whether to deploy the TVC app in debug mode, which includes additional logging and debugging tools. Default is false.
	DebugMode *bool `json:"debugMode,omitempty"`

	// Digest of the pivot binary in the pivot container. This value will be inserted in the QOS manifest to ensure application integrity.
	// Required: true
	ExpectedPivotDigest *string `json:"expectedPivotDigest"`

	// Optional nonce to ensure uniqueness of the deployment manifest. If not provided, it defaults to the current Unix timestamp in seconds.
	Nonce *int64 `json:"nonce,omitempty"`

	// Arguments to pass to the pivot binary at startup. Encoded as a list of strings, for example ["--foo", "bar"]
	// Required: true
	PivotArgs []string `json:"pivotArgs"`

	// Address(es) on which the pivot binary listens. A bind address can be a port alone (e.g. "3000") or an ip:port (e.g. "127.0.0.1:3000"). If provided as a port alone, the IP is assumed to be 0.0.0.0
	PivotBindAddresses []string `json:"pivotBindAddresses"`

	// Optional encrypted pull secret to authorize Turnkey to pull the pivot container image. If your image is public, leave this empty.
	PivotContainerEncryptedPullSecret *string `json:"pivotContainerEncryptedPullSecret,omitempty"`

	// URL of the container containing the pivot binary
	// Required: true
	PivotContainerImageURL *string `json:"pivotContainerImageUrl"`

	// Location of the binary in the pivot container
	// Required: true
	PivotPath *string `json:"pivotPath"`

	// The QuorumOS version to use to deploy this application
	// Required: true
	QosVersion *string `json:"qosVersion"`
}

// Validate validates this create tvc deployment intent
func (m *CreateTvcDeploymentIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpectedPivotDigest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePivotArgs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePivotContainerImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePivotPath(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQosVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTvcDeploymentIntent) validateAppID(formats strfmt.Registry) error {

	if err := validate.Required("appId", "body", m.AppID); err != nil {
		return err
	}

	return nil
}

func (m *CreateTvcDeploymentIntent) validateExpectedPivotDigest(formats strfmt.Registry) error {

	if err := validate.Required("expectedPivotDigest", "body", m.ExpectedPivotDigest); err != nil {
		return err
	}

	return nil
}

func (m *CreateTvcDeploymentIntent) validatePivotArgs(formats strfmt.Registry) error {

	if err := validate.Required("pivotArgs", "body", m.PivotArgs); err != nil {
		return err
	}

	return nil
}

func (m *CreateTvcDeploymentIntent) validatePivotContainerImageURL(formats strfmt.Registry) error {

	if err := validate.Required("pivotContainerImageUrl", "body", m.PivotContainerImageURL); err != nil {
		return err
	}

	return nil
}

func (m *CreateTvcDeploymentIntent) validatePivotPath(formats strfmt.Registry) error {

	if err := validate.Required("pivotPath", "body", m.PivotPath); err != nil {
		return err
	}

	return nil
}

func (m *CreateTvcDeploymentIntent) validateQosVersion(formats strfmt.Registry) error {

	if err := validate.Required("qosVersion", "body", m.QosVersion); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create tvc deployment intent based on context it is used
func (m *CreateTvcDeploymentIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTvcDeploymentIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTvcDeploymentIntent) UnmarshalBinary(b []byte) error {
	var res CreateTvcDeploymentIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
