// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAPIKeyResponse get Api key response
//
// swagger:model GetApiKeyResponse
type GetAPIKeyResponse struct {

	// An API key.
	// Required: true
	APIKey *APIKey `json:"apiKey"`
}

// Validate validates this get Api key response
func (m *GetAPIKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAPIKeyResponse) validateAPIKey(formats strfmt.Registry) error {

	if err := validate.Required("apiKey", "body", m.APIKey); err != nil {
		return err
	}

	if m.APIKey != nil {
		if err := m.APIKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiKey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiKey")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get Api key response based on the context it is used
func (m *GetAPIKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAPIKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAPIKeyResponse) contextValidateAPIKey(ctx context.Context, formats strfmt.Registry) error {

	if m.APIKey != nil {

		if err := m.APIKey.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apiKey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apiKey")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetAPIKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAPIKeyResponse) UnmarshalBinary(b []byte) error {
	var res GetAPIKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
