// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAPIKeyRequest get Api key request
//
// swagger:model GetApiKeyRequest
type GetAPIKeyRequest struct {

	// Unique identifier for a given API key.
	// Required: true
	APIKeyID *string `json:"apiKeyId"`

	// Unique identifier for a given Organization.
	// Required: true
	OrganizationID *string `json:"organizationId"`
}

// Validate validates this get Api key request
func (m *GetAPIKeyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAPIKeyRequest) validateAPIKeyID(formats strfmt.Registry) error {

	if err := validate.Required("apiKeyId", "body", m.APIKeyID); err != nil {
		return err
	}

	return nil
}

func (m *GetAPIKeyRequest) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get Api key request based on context it is used
func (m *GetAPIKeyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetAPIKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAPIKeyRequest) UnmarshalBinary(b []byte) error {
	var res GetAPIKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
