// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSmartContractInterfaceResponse get smart contract interface response
//
// swagger:model GetSmartContractInterfaceResponse
type GetSmartContractInterfaceResponse struct {

	// Object to be used in conjunction with policies to guard transaction signing.
	// Required: true
	SmartContractInterface *DataV1SmartContractInterface `json:"smartContractInterface"`
}

// Validate validates this get smart contract interface response
func (m *GetSmartContractInterfaceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSmartContractInterface(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSmartContractInterfaceResponse) validateSmartContractInterface(formats strfmt.Registry) error {

	if err := validate.Required("smartContractInterface", "body", m.SmartContractInterface); err != nil {
		return err
	}

	if m.SmartContractInterface != nil {
		if err := m.SmartContractInterface.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("smartContractInterface")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("smartContractInterface")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get smart contract interface response based on the context it is used
func (m *GetSmartContractInterfaceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSmartContractInterface(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSmartContractInterfaceResponse) contextValidateSmartContractInterface(ctx context.Context, formats strfmt.Registry) error {

	if m.SmartContractInterface != nil {

		if err := m.SmartContractInterface.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("smartContractInterface")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("smartContractInterface")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetSmartContractInterfaceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSmartContractInterfaceResponse) UnmarshalBinary(b []byte) error {
	var res GetSmartContractInterfaceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
