// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetActivitiesRequest get activities request
//
// swagger:model GetActivitiesRequest
type GetActivitiesRequest struct {

	// Array of activity statuses filtering which activities will be listed in the response.
	FilterByStatus []ActivityStatus `json:"filterByStatus"`

	// Array of activity types filtering which activities will be listed in the response.
	FilterByType []ActivityType `json:"filterByType"`

	// Unique identifier for a given organization.
	// Required: true
	OrganizationID *string `json:"organizationId"`

	// Parameters used for cursor-based pagination.
	PaginationOptions *Pagination `json:"paginationOptions,omitempty"`
}

// Validate validates this get activities request
func (m *GetActivitiesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilterByStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilterByType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaginationOptions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetActivitiesRequest) validateFilterByStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.FilterByStatus) { // not required
		return nil
	}

	for i := 0; i < len(m.FilterByStatus); i++ {

		if err := m.FilterByStatus[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filterByStatus" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filterByStatus" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *GetActivitiesRequest) validateFilterByType(formats strfmt.Registry) error {
	if swag.IsZero(m.FilterByType) { // not required
		return nil
	}

	for i := 0; i < len(m.FilterByType); i++ {

		if err := m.FilterByType[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filterByType" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filterByType" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *GetActivitiesRequest) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

func (m *GetActivitiesRequest) validatePaginationOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.PaginationOptions) { // not required
		return nil
	}

	if m.PaginationOptions != nil {
		if err := m.PaginationOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paginationOptions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paginationOptions")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get activities request based on the context it is used
func (m *GetActivitiesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilterByStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFilterByType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePaginationOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetActivitiesRequest) contextValidateFilterByStatus(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FilterByStatus); i++ {

		if swag.IsZero(m.FilterByStatus[i]) { // not required
			return nil
		}

		if err := m.FilterByStatus[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filterByStatus" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filterByStatus" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *GetActivitiesRequest) contextValidateFilterByType(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FilterByType); i++ {

		if swag.IsZero(m.FilterByType[i]) { // not required
			return nil
		}

		if err := m.FilterByType[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filterByType" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filterByType" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *GetActivitiesRequest) contextValidatePaginationOptions(ctx context.Context, formats strfmt.Registry) error {

	if m.PaginationOptions != nil {

		if swag.IsZero(m.PaginationOptions) { // not required
			return nil
		}

		if err := m.PaginationOptions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paginationOptions")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paginationOptions")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetActivitiesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetActivitiesRequest) UnmarshalBinary(b []byte) error {
	var res GetActivitiesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
