// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetNoncesResponse get nonces response
//
// swagger:model GetNoncesResponse
type GetNoncesResponse struct {

	// The gas station nonce for sponsored transactions, if requested.
	GasStationNonce *string `json:"gasStationNonce,omitempty"`

	// The standard on-chain nonce for the address, if requested.
	Nonce *string `json:"nonce,omitempty"`
}

// Validate validates this get nonces response
func (m *GetNoncesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get nonces response based on context it is used
func (m *GetNoncesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetNoncesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNoncesResponse) UnmarshalBinary(b []byte) error {
	var res GetNoncesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
