// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NOOPCodegenAnchorResponse n o o p codegen anchor response
//
// swagger:model NOOPCodegenAnchorResponse
type NOOPCodegenAnchorResponse struct {

	// stamp
	// Required: true
	Stamp *WebAuthnStamp `json:"stamp"`

	// token usage
	TokenUsage *TokenUsage `json:"tokenUsage,omitempty"`
}

// Validate validates this n o o p codegen anchor response
func (m *NOOPCodegenAnchorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenUsage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NOOPCodegenAnchorResponse) validateStamp(formats strfmt.Registry) error {

	if err := validate.Required("stamp", "body", m.Stamp); err != nil {
		return err
	}

	if m.Stamp != nil {
		if err := m.Stamp.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stamp")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stamp")
			}
			return err
		}
	}

	return nil
}

func (m *NOOPCodegenAnchorResponse) validateTokenUsage(formats strfmt.Registry) error {
	if swag.IsZero(m.TokenUsage) { // not required
		return nil
	}

	if m.TokenUsage != nil {
		if err := m.TokenUsage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenUsage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenUsage")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this n o o p codegen anchor response based on the context it is used
func (m *NOOPCodegenAnchorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStamp(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTokenUsage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NOOPCodegenAnchorResponse) contextValidateStamp(ctx context.Context, formats strfmt.Registry) error {

	if m.Stamp != nil {

		if err := m.Stamp.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stamp")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stamp")
			}
			return err
		}
	}

	return nil
}

func (m *NOOPCodegenAnchorResponse) contextValidateTokenUsage(ctx context.Context, formats strfmt.Registry) error {

	if m.TokenUsage != nil {

		if swag.IsZero(m.TokenUsage) { // not required
			return nil
		}

		if err := m.TokenUsage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tokenUsage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tokenUsage")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NOOPCodegenAnchorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NOOPCodegenAnchorResponse) UnmarshalBinary(b []byte) error {
	var res NOOPCodegenAnchorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
