// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdatePrivateKeyTagIntent update private key tag intent
//
// swagger:model UpdatePrivateKeyTagIntent
type UpdatePrivateKeyTagIntent struct {

	// A list of Private Keys IDs to add this tag to.
	// Required: true
	AddPrivateKeyIds []string `json:"addPrivateKeyIds"`

	// The new, human-readable name for the tag with the given ID.
	NewPrivateKeyTagName *string `json:"newPrivateKeyTagName,omitempty"`

	// Unique identifier for a given Private Key Tag.
	// Required: true
	PrivateKeyTagID *string `json:"privateKeyTagId"`

	// A list of Private Key IDs to remove this tag from.
	// Required: true
	RemovePrivateKeyIds []string `json:"removePrivateKeyIds"`
}

// Validate validates this update private key tag intent
func (m *UpdatePrivateKeyTagIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddPrivateKeyIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateKeyTagID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemovePrivateKeyIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdatePrivateKeyTagIntent) validateAddPrivateKeyIds(formats strfmt.Registry) error {

	if err := validate.Required("addPrivateKeyIds", "body", m.AddPrivateKeyIds); err != nil {
		return err
	}

	return nil
}

func (m *UpdatePrivateKeyTagIntent) validatePrivateKeyTagID(formats strfmt.Registry) error {

	if err := validate.Required("privateKeyTagId", "body", m.PrivateKeyTagID); err != nil {
		return err
	}

	return nil
}

func (m *UpdatePrivateKeyTagIntent) validateRemovePrivateKeyIds(formats strfmt.Registry) error {

	if err := validate.Required("removePrivateKeyIds", "body", m.RemovePrivateKeyIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update private key tag intent based on context it is used
func (m *UpdatePrivateKeyTagIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdatePrivateKeyTagIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdatePrivateKeyTagIntent) UnmarshalBinary(b []byte) error {
	var res UpdatePrivateKeyTagIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
