// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateFiatOnRampCredentialIntent update fiat on ramp credential intent
//
// swagger:model UpdateFiatOnRampCredentialIntent
type UpdateFiatOnRampCredentialIntent struct {

	// Private API key for the on-ramp provider encrypted to our on-ramp encryption public key. Some providers, like Coinbase, require this additional key.
	EncryptedPrivateAPIKey *string `json:"encryptedPrivateApiKey,omitempty"`

	// Secret API key for the on-ramp provider encrypted to our on-ramp encryption public key
	// Required: true
	EncryptedSecretAPIKey *string `json:"encryptedSecretApiKey"`

	// The ID of the fiat on-ramp credential to update
	// Required: true
	FiatOnrampCredentialID *string `json:"fiatOnrampCredentialId"`

	// The fiat on-ramp provider
	// Required: true
	OnrampProvider *FiatOnRampProvider `json:"onrampProvider"`

	// Project ID for the on-ramp provider. Some providers, like Coinbase, require this additional identifier.
	ProjectID *string `json:"projectId,omitempty"`

	// Publishable API key for the on-ramp provider
	// Required: true
	PublishableAPIKey *string `json:"publishableApiKey"`
}

// Validate validates this update fiat on ramp credential intent
func (m *UpdateFiatOnRampCredentialIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEncryptedSecretAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFiatOnrampCredentialID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnrampProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublishableAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateFiatOnRampCredentialIntent) validateEncryptedSecretAPIKey(formats strfmt.Registry) error {

	if err := validate.Required("encryptedSecretApiKey", "body", m.EncryptedSecretAPIKey); err != nil {
		return err
	}

	return nil
}

func (m *UpdateFiatOnRampCredentialIntent) validateFiatOnrampCredentialID(formats strfmt.Registry) error {

	if err := validate.Required("fiatOnrampCredentialId", "body", m.FiatOnrampCredentialID); err != nil {
		return err
	}

	return nil
}

func (m *UpdateFiatOnRampCredentialIntent) validateOnrampProvider(formats strfmt.Registry) error {

	if err := validate.Required("onrampProvider", "body", m.OnrampProvider); err != nil {
		return err
	}

	if err := validate.Required("onrampProvider", "body", m.OnrampProvider); err != nil {
		return err
	}

	if m.OnrampProvider != nil {
		if err := m.OnrampProvider.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("onrampProvider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("onrampProvider")
			}
			return err
		}
	}

	return nil
}

func (m *UpdateFiatOnRampCredentialIntent) validatePublishableAPIKey(formats strfmt.Registry) error {

	if err := validate.Required("publishableApiKey", "body", m.PublishableAPIKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this update fiat on ramp credential intent based on the context it is used
func (m *UpdateFiatOnRampCredentialIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOnrampProvider(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateFiatOnRampCredentialIntent) contextValidateOnrampProvider(ctx context.Context, formats strfmt.Registry) error {

	if m.OnrampProvider != nil {

		if err := m.OnrampProvider.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("onrampProvider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("onrampProvider")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateFiatOnRampCredentialIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateFiatOnRampCredentialIntent) UnmarshalBinary(b []byte) error {
	var res UpdateFiatOnRampCredentialIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
