// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// WebauthnV1AuthenticatorTransport webauthn v1 authenticator transport
//
// swagger:model webauthn.v1.AuthenticatorTransport
type WebauthnV1AuthenticatorTransport string

func NewWebauthnV1AuthenticatorTransport(value WebauthnV1AuthenticatorTransport) *WebauthnV1AuthenticatorTransport {
	return &value
}

// Pointer returns a pointer to a freshly-allocated WebauthnV1AuthenticatorTransport.
func (m WebauthnV1AuthenticatorTransport) Pointer() *WebauthnV1AuthenticatorTransport {
	return &m
}

const (

	// AuthenticatorTransportBle captures enum value "AUTHENTICATOR_TRANSPORT_BLE"
	AuthenticatorTransportBle WebauthnV1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_BLE"

	// AuthenticatorTransportInternal captures enum value "AUTHENTICATOR_TRANSPORT_INTERNAL"
	AuthenticatorTransportInternal WebauthnV1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_INTERNAL"

	// AuthenticatorTransportNfc captures enum value "AUTHENTICATOR_TRANSPORT_NFC"
	AuthenticatorTransportNfc WebauthnV1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_NFC"

	// AuthenticatorTransportUsb captures enum value "AUTHENTICATOR_TRANSPORT_USB"
	AuthenticatorTransportUsb WebauthnV1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_USB"

	// AuthenticatorTransportHybrid captures enum value "AUTHENTICATOR_TRANSPORT_HYBRID"
	AuthenticatorTransportHybrid WebauthnV1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_HYBRID"
)

// for schema
var WebauthnV1AuthenticatorTransportEnum []WebauthnV1AuthenticatorTransport

func init() {
	var res []WebauthnV1AuthenticatorTransport
	if err := json.Unmarshal([]byte(`["AUTHENTICATOR_TRANSPORT_BLE","AUTHENTICATOR_TRANSPORT_INTERNAL","AUTHENTICATOR_TRANSPORT_NFC","AUTHENTICATOR_TRANSPORT_USB","AUTHENTICATOR_TRANSPORT_HYBRID"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		WebauthnV1AuthenticatorTransportEnum = append(WebauthnV1AuthenticatorTransportEnum, v)
	}
}

func (m WebauthnV1AuthenticatorTransport) validateWebauthnV1AuthenticatorTransportEnum(path, location string, value WebauthnV1AuthenticatorTransport) error {
	if err := validate.EnumCase(path, location, value, WebauthnV1AuthenticatorTransportEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this webauthn v1 authenticator transport
func (m WebauthnV1AuthenticatorTransport) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateWebauthnV1AuthenticatorTransportEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this webauthn v1 authenticator transport based on context it is used
func (m WebauthnV1AuthenticatorTransport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
