// Code generated by go-swagger; DO NOT EDIT.

package user_recovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewPublicAPIServiceInitUserEmailRecoveryParams creates a new PublicAPIServiceInitUserEmailRecoveryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceInitUserEmailRecoveryParams() *PublicAPIServiceInitUserEmailRecoveryParams {
	return &PublicAPIServiceInitUserEmailRecoveryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceInitUserEmailRecoveryParamsWithTimeout creates a new PublicAPIServiceInitUserEmailRecoveryParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceInitUserEmailRecoveryParamsWithTimeout(timeout time.Duration) *PublicAPIServiceInitUserEmailRecoveryParams {
	return &PublicAPIServiceInitUserEmailRecoveryParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceInitUserEmailRecoveryParamsWithContext creates a new PublicAPIServiceInitUserEmailRecoveryParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceInitUserEmailRecoveryParamsWithContext(ctx context.Context) *PublicAPIServiceInitUserEmailRecoveryParams {
	return &PublicAPIServiceInitUserEmailRecoveryParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceInitUserEmailRecoveryParamsWithHTTPClient creates a new PublicAPIServiceInitUserEmailRecoveryParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceInitUserEmailRecoveryParamsWithHTTPClient(client *http.Client) *PublicAPIServiceInitUserEmailRecoveryParams {
	return &PublicAPIServiceInitUserEmailRecoveryParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceInitUserEmailRecoveryParams contains all the parameters to send to the API endpoint

	for the public Api service init user email recovery operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceInitUserEmailRecoveryParams struct {

	// Body.
	Body *models.V1InitUserEmailRecoveryRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service init user email recovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WithDefaults() *PublicAPIServiceInitUserEmailRecoveryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service init user email recovery params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceInitUserEmailRecoveryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WithTimeout(timeout time.Duration) *PublicAPIServiceInitUserEmailRecoveryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WithContext(ctx context.Context) *PublicAPIServiceInitUserEmailRecoveryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WithHTTPClient(client *http.Client) *PublicAPIServiceInitUserEmailRecoveryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WithBody(body *models.V1InitUserEmailRecoveryRequest) *PublicAPIServiceInitUserEmailRecoveryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service init user email recovery params
func (o *PublicAPIServiceInitUserEmailRecoveryParams) SetBody(body *models.V1InitUserEmailRecoveryRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceInitUserEmailRecoveryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
