// Code generated by go-swagger; DO NOT EDIT.

package on_ramp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewGetOnRampTransactionStatusParams creates a new GetOnRampTransactionStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOnRampTransactionStatusParams() *GetOnRampTransactionStatusParams {
	return &GetOnRampTransactionStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOnRampTransactionStatusParamsWithTimeout creates a new GetOnRampTransactionStatusParams object
// with the ability to set a timeout on a request.
func NewGetOnRampTransactionStatusParamsWithTimeout(timeout time.Duration) *GetOnRampTransactionStatusParams {
	return &GetOnRampTransactionStatusParams{
		timeout: timeout,
	}
}

// NewGetOnRampTransactionStatusParamsWithContext creates a new GetOnRampTransactionStatusParams object
// with the ability to set a context for a request.
func NewGetOnRampTransactionStatusParamsWithContext(ctx context.Context) *GetOnRampTransactionStatusParams {
	return &GetOnRampTransactionStatusParams{
		Context: ctx,
	}
}

// NewGetOnRampTransactionStatusParamsWithHTTPClient creates a new GetOnRampTransactionStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOnRampTransactionStatusParamsWithHTTPClient(client *http.Client) *GetOnRampTransactionStatusParams {
	return &GetOnRampTransactionStatusParams{
		HTTPClient: client,
	}
}

/*
GetOnRampTransactionStatusParams contains all the parameters to send to the API endpoint

	for the get on ramp transaction status operation.

	Typically these are written to a http.Request.
*/
type GetOnRampTransactionStatusParams struct {

	// Body.
	Body *models.GetOnRampTransactionStatusRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get on ramp transaction status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOnRampTransactionStatusParams) WithDefaults() *GetOnRampTransactionStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get on ramp transaction status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOnRampTransactionStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) WithTimeout(timeout time.Duration) *GetOnRampTransactionStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) WithContext(ctx context.Context) *GetOnRampTransactionStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) WithHTTPClient(client *http.Client) *GetOnRampTransactionStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) WithBody(body *models.GetOnRampTransactionStatusRequest) *GetOnRampTransactionStatusParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get on ramp transaction status params
func (o *GetOnRampTransactionStatusParams) SetBody(body *models.GetOnRampTransactionStatusRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetOnRampTransactionStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
