// Code generated by go-swagger; DO NOT EDIT.

package on_ramp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// InitFiatOnRampReader is a Reader for the InitFiatOnRamp structure.
type InitFiatOnRampReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitFiatOnRampReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInitFiatOnRampOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/init_fiat_on_ramp] InitFiatOnRamp", response, response.Code())
	}
}

// NewInitFiatOnRampOK creates a InitFiatOnRampOK with default headers values
func NewInitFiatOnRampOK() *InitFiatOnRampOK {
	return &InitFiatOnRampOK{}
}

/*
InitFiatOnRampOK describes a response with status code 200, with default header values.

A successful response.
*/
type InitFiatOnRampOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this init fiat on ramp o k response has a 2xx status code
func (o *InitFiatOnRampOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this init fiat on ramp o k response has a 3xx status code
func (o *InitFiatOnRampOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this init fiat on ramp o k response has a 4xx status code
func (o *InitFiatOnRampOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this init fiat on ramp o k response has a 5xx status code
func (o *InitFiatOnRampOK) IsServerError() bool {
	return false
}

// IsCode returns true when this init fiat on ramp o k response a status code equal to that given
func (o *InitFiatOnRampOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the init fiat on ramp o k response
func (o *InitFiatOnRampOK) Code() int {
	return 200
}

func (o *InitFiatOnRampOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/init_fiat_on_ramp][%d] initFiatOnRampOK  %+v", 200, o.Payload)
}

func (o *InitFiatOnRampOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/init_fiat_on_ramp][%d] initFiatOnRampOK  %+v", 200, o.Payload)
}

func (o *InitFiatOnRampOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *InitFiatOnRampOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
