// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewCreateSmartContractInterfaceParams creates a new CreateSmartContractInterfaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSmartContractInterfaceParams() *CreateSmartContractInterfaceParams {
	return &CreateSmartContractInterfaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSmartContractInterfaceParamsWithTimeout creates a new CreateSmartContractInterfaceParams object
// with the ability to set a timeout on a request.
func NewCreateSmartContractInterfaceParamsWithTimeout(timeout time.Duration) *CreateSmartContractInterfaceParams {
	return &CreateSmartContractInterfaceParams{
		timeout: timeout,
	}
}

// NewCreateSmartContractInterfaceParamsWithContext creates a new CreateSmartContractInterfaceParams object
// with the ability to set a context for a request.
func NewCreateSmartContractInterfaceParamsWithContext(ctx context.Context) *CreateSmartContractInterfaceParams {
	return &CreateSmartContractInterfaceParams{
		Context: ctx,
	}
}

// NewCreateSmartContractInterfaceParamsWithHTTPClient creates a new CreateSmartContractInterfaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSmartContractInterfaceParamsWithHTTPClient(client *http.Client) *CreateSmartContractInterfaceParams {
	return &CreateSmartContractInterfaceParams{
		HTTPClient: client,
	}
}

/*
CreateSmartContractInterfaceParams contains all the parameters to send to the API endpoint

	for the create smart contract interface operation.

	Typically these are written to a http.Request.
*/
type CreateSmartContractInterfaceParams struct {

	// Body.
	Body *models.CreateSmartContractInterfaceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create smart contract interface params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSmartContractInterfaceParams) WithDefaults() *CreateSmartContractInterfaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create smart contract interface params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSmartContractInterfaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) WithTimeout(timeout time.Duration) *CreateSmartContractInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) WithContext(ctx context.Context) *CreateSmartContractInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) WithHTTPClient(client *http.Client) *CreateSmartContractInterfaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) WithBody(body *models.CreateSmartContractInterfaceRequest) *CreateSmartContractInterfaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create smart contract interface params
func (o *CreateSmartContractInterfaceParams) SetBody(body *models.CreateSmartContractInterfaceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSmartContractInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
