// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// CreateSmartContractInterfaceReader is a Reader for the CreateSmartContractInterface structure.
type CreateSmartContractInterfaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSmartContractInterfaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSmartContractInterfaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/create_smart_contract_interface] CreateSmartContractInterface", response, response.Code())
	}
}

// NewCreateSmartContractInterfaceOK creates a CreateSmartContractInterfaceOK with default headers values
func NewCreateSmartContractInterfaceOK() *CreateSmartContractInterfaceOK {
	return &CreateSmartContractInterfaceOK{}
}

/*
CreateSmartContractInterfaceOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateSmartContractInterfaceOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this create smart contract interface o k response has a 2xx status code
func (o *CreateSmartContractInterfaceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create smart contract interface o k response has a 3xx status code
func (o *CreateSmartContractInterfaceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create smart contract interface o k response has a 4xx status code
func (o *CreateSmartContractInterfaceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create smart contract interface o k response has a 5xx status code
func (o *CreateSmartContractInterfaceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create smart contract interface o k response a status code equal to that given
func (o *CreateSmartContractInterfaceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create smart contract interface o k response
func (o *CreateSmartContractInterfaceOK) Code() int {
	return 200
}

func (o *CreateSmartContractInterfaceOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_smart_contract_interface][%d] createSmartContractInterfaceOK  %+v", 200, o.Payload)
}

func (o *CreateSmartContractInterfaceOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_smart_contract_interface][%d] createSmartContractInterfaceOK  %+v", 200, o.Payload)
}

func (o *CreateSmartContractInterfaceOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *CreateSmartContractInterfaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
