// Code generated by go-swagger; DO NOT EDIT.

package user_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewEmailAuthParams creates a new EmailAuthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEmailAuthParams() *EmailAuthParams {
	return &EmailAuthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEmailAuthParamsWithTimeout creates a new EmailAuthParams object
// with the ability to set a timeout on a request.
func NewEmailAuthParamsWithTimeout(timeout time.Duration) *EmailAuthParams {
	return &EmailAuthParams{
		timeout: timeout,
	}
}

// NewEmailAuthParamsWithContext creates a new EmailAuthParams object
// with the ability to set a context for a request.
func NewEmailAuthParamsWithContext(ctx context.Context) *EmailAuthParams {
	return &EmailAuthParams{
		Context: ctx,
	}
}

// NewEmailAuthParamsWithHTTPClient creates a new EmailAuthParams object
// with the ability to set a custom HTTPClient for a request.
func NewEmailAuthParamsWithHTTPClient(client *http.Client) *EmailAuthParams {
	return &EmailAuthParams{
		HTTPClient: client,
	}
}

/*
EmailAuthParams contains all the parameters to send to the API endpoint

	for the email auth operation.

	Typically these are written to a http.Request.
*/
type EmailAuthParams struct {

	// Body.
	Body *models.EmailAuthRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the email auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EmailAuthParams) WithDefaults() *EmailAuthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the email auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EmailAuthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the email auth params
func (o *EmailAuthParams) WithTimeout(timeout time.Duration) *EmailAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the email auth params
func (o *EmailAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the email auth params
func (o *EmailAuthParams) WithContext(ctx context.Context) *EmailAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the email auth params
func (o *EmailAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the email auth params
func (o *EmailAuthParams) WithHTTPClient(client *http.Client) *EmailAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the email auth params
func (o *EmailAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the email auth params
func (o *EmailAuthParams) WithBody(body *models.EmailAuthRequest) *EmailAuthParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the email auth params
func (o *EmailAuthParams) SetBody(body *models.EmailAuthRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EmailAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
