// Code generated by go-swagger; DO NOT EDIT.

package user_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewGetOauthProvidersParams creates a new GetOauthProvidersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOauthProvidersParams() *GetOauthProvidersParams {
	return &GetOauthProvidersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOauthProvidersParamsWithTimeout creates a new GetOauthProvidersParams object
// with the ability to set a timeout on a request.
func NewGetOauthProvidersParamsWithTimeout(timeout time.Duration) *GetOauthProvidersParams {
	return &GetOauthProvidersParams{
		timeout: timeout,
	}
}

// NewGetOauthProvidersParamsWithContext creates a new GetOauthProvidersParams object
// with the ability to set a context for a request.
func NewGetOauthProvidersParamsWithContext(ctx context.Context) *GetOauthProvidersParams {
	return &GetOauthProvidersParams{
		Context: ctx,
	}
}

// NewGetOauthProvidersParamsWithHTTPClient creates a new GetOauthProvidersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOauthProvidersParamsWithHTTPClient(client *http.Client) *GetOauthProvidersParams {
	return &GetOauthProvidersParams{
		HTTPClient: client,
	}
}

/*
GetOauthProvidersParams contains all the parameters to send to the API endpoint

	for the get oauth providers operation.

	Typically these are written to a http.Request.
*/
type GetOauthProvidersParams struct {

	// Body.
	Body *models.GetOauthProvidersRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get oauth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOauthProvidersParams) WithDefaults() *GetOauthProvidersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get oauth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOauthProvidersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get oauth providers params
func (o *GetOauthProvidersParams) WithTimeout(timeout time.Duration) *GetOauthProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oauth providers params
func (o *GetOauthProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oauth providers params
func (o *GetOauthProvidersParams) WithContext(ctx context.Context) *GetOauthProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oauth providers params
func (o *GetOauthProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oauth providers params
func (o *GetOauthProvidersParams) WithHTTPClient(client *http.Client) *GetOauthProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oauth providers params
func (o *GetOauthProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get oauth providers params
func (o *GetOauthProvidersParams) WithBody(body *models.GetOauthProvidersRequest) *GetOauthProvidersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get oauth providers params
func (o *GetOauthProvidersParams) SetBody(body *models.GetOauthProvidersRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetOauthProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
