// Code generated by go-swagger; DO NOT EDIT.

package user_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewCreateUserTagParams creates a new CreateUserTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateUserTagParams() *CreateUserTagParams {
	return &CreateUserTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUserTagParamsWithTimeout creates a new CreateUserTagParams object
// with the ability to set a timeout on a request.
func NewCreateUserTagParamsWithTimeout(timeout time.Duration) *CreateUserTagParams {
	return &CreateUserTagParams{
		timeout: timeout,
	}
}

// NewCreateUserTagParamsWithContext creates a new CreateUserTagParams object
// with the ability to set a context for a request.
func NewCreateUserTagParamsWithContext(ctx context.Context) *CreateUserTagParams {
	return &CreateUserTagParams{
		Context: ctx,
	}
}

// NewCreateUserTagParamsWithHTTPClient creates a new CreateUserTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateUserTagParamsWithHTTPClient(client *http.Client) *CreateUserTagParams {
	return &CreateUserTagParams{
		HTTPClient: client,
	}
}

/*
CreateUserTagParams contains all the parameters to send to the API endpoint

	for the create user tag operation.

	Typically these are written to a http.Request.
*/
type CreateUserTagParams struct {

	// Body.
	Body *models.CreateUserTagRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create user tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserTagParams) WithDefaults() *CreateUserTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create user tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create user tag params
func (o *CreateUserTagParams) WithTimeout(timeout time.Duration) *CreateUserTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create user tag params
func (o *CreateUserTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create user tag params
func (o *CreateUserTagParams) WithContext(ctx context.Context) *CreateUserTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create user tag params
func (o *CreateUserTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create user tag params
func (o *CreateUserTagParams) WithHTTPClient(client *http.Client) *CreateUserTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create user tag params
func (o *CreateUserTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create user tag params
func (o *CreateUserTagParams) WithBody(body *models.CreateUserTagRequest) *CreateUserTagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create user tag params
func (o *CreateUserTagParams) SetBody(body *models.CreateUserTagRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUserTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
