// Code generated by go-swagger; DO NOT EDIT.

package user_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// NewPublicAPIServiceCreateUserTagParams creates a new PublicAPIServiceCreateUserTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceCreateUserTagParams() *PublicAPIServiceCreateUserTagParams {
	return &PublicAPIServiceCreateUserTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceCreateUserTagParamsWithTimeout creates a new PublicAPIServiceCreateUserTagParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceCreateUserTagParamsWithTimeout(timeout time.Duration) *PublicAPIServiceCreateUserTagParams {
	return &PublicAPIServiceCreateUserTagParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceCreateUserTagParamsWithContext creates a new PublicAPIServiceCreateUserTagParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceCreateUserTagParamsWithContext(ctx context.Context) *PublicAPIServiceCreateUserTagParams {
	return &PublicAPIServiceCreateUserTagParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceCreateUserTagParamsWithHTTPClient creates a new PublicAPIServiceCreateUserTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceCreateUserTagParamsWithHTTPClient(client *http.Client) *PublicAPIServiceCreateUserTagParams {
	return &PublicAPIServiceCreateUserTagParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceCreateUserTagParams contains all the parameters to send to the API endpoint

	for the public Api service create user tag operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceCreateUserTagParams struct {

	// Body.
	Body *models.V1CreateUserTagRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service create user tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreateUserTagParams) WithDefaults() *PublicAPIServiceCreateUserTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service create user tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreateUserTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) WithTimeout(timeout time.Duration) *PublicAPIServiceCreateUserTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) WithContext(ctx context.Context) *PublicAPIServiceCreateUserTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) WithHTTPClient(client *http.Client) *PublicAPIServiceCreateUserTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) WithBody(body *models.V1CreateUserTagRequest) *PublicAPIServiceCreateUserTagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service create user tag params
func (o *PublicAPIServiceCreateUserTagParams) SetBody(body *models.V1CreateUserTagRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceCreateUserTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
