// Code generated by go-swagger; DO NOT EDIT.

package send_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/go-sdk/pkg/api/models"
)

// GetSendTransactionStatusReader is a Reader for the GetSendTransactionStatus structure.
type GetSendTransactionStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSendTransactionStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSendTransactionStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_send_transaction_status] GetSendTransactionStatus", response, response.Code())
	}
}

// NewGetSendTransactionStatusOK creates a GetSendTransactionStatusOK with default headers values
func NewGetSendTransactionStatusOK() *GetSendTransactionStatusOK {
	return &GetSendTransactionStatusOK{}
}

/*
GetSendTransactionStatusOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetSendTransactionStatusOK struct {
	Payload *models.GetSendTransactionStatusResponse
}

// IsSuccess returns true when this get send transaction status o k response has a 2xx status code
func (o *GetSendTransactionStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get send transaction status o k response has a 3xx status code
func (o *GetSendTransactionStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get send transaction status o k response has a 4xx status code
func (o *GetSendTransactionStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get send transaction status o k response has a 5xx status code
func (o *GetSendTransactionStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get send transaction status o k response a status code equal to that given
func (o *GetSendTransactionStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get send transaction status o k response
func (o *GetSendTransactionStatusOK) Code() int {
	return 200
}

func (o *GetSendTransactionStatusOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_send_transaction_status][%d] getSendTransactionStatusOK  %+v", 200, o.Payload)
}

func (o *GetSendTransactionStatusOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_send_transaction_status][%d] getSendTransactionStatusOK  %+v", 200, o.Payload)
}

func (o *GetSendTransactionStatusOK) GetPayload() *models.GetSendTransactionStatusResponse {
	return o.Payload
}

func (o *GetSendTransactionStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSendTransactionStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
